### ISSUE TITLE
Patterns["ISIS"] is not usable

### ISSUE THREAD

**Issue by cpuwolf** [Fragtality/PilotsDeck_FNX#3]
Env: MSFS SU11+ Fenix A320 v1.0.6.146
Patterns["ISIS"] I always got false and 1013. so BARO data are not usable. Thank you

**Comment by Fragtality** [comment]
Always can't be true - I've tested with SU11/1.0.6 initially and just retested it: The ISIS Barometer was working and could also be switchted to STD.
Maybe there are now variations in the Location which I don't have yet included, but it should be working sometimes at least.

Are you sure the Binary is working properly? Do other Values work? (Only the second Battery does not work at all currently)

Or maybe your Loading Times are very long so you don't press "ready to fly" in time. Try to stop and start the Binary manually when the Session is completely loaded (sitting at the Gate). Does it work then?

**Comment by cpuwolf** [comment]
Thanks.
I have  tested to start it very later, I have confirmed FenixSystem is ready. I still get false and 1013 fixed values of Patterns["ISIS"]

FCU SPD
FCU HDG
FCU HDG FMA
FCU ALT
FCU VS
FCU VS FMA

these values are Good,

**Comment by Fragtality** [comment]
Very later? No need to wait extra long or anything like that, it is just important that the initial scan is done when the session is really running (otherwise some locations are not found).
Why would you need to confirm that FenixSystem is ready as an average user? And how do you confirm that?
And when you say "still get false" - you mean the Offset is always zero?

Could you explain how you're are using the binary exactly? I somehow have the suspicion you're using it in a different use-case than it is designed for ...

**Comment by cpuwolf** [comment]
Because I am debugging your source code to adapt my environment.

ElementManager: Offset for <isisBaro> is at 0x542C:6:s
MemoryScanner: Pattern Search took 0.192883s
Program: Pattern <ISIS> is at Address 0x5CC683C (97282108)

looks like location is found

**Comment by Fragtality** [comment]
Well, maybe it would have been wiser to start with that ;)

It normally does not make a difference when a debugger is attached - but did you try it without debugging?

In your initial Description you've said either it is false or 1013? Maybe it is have something to do with the way you are reading that Offset? It can be 6 characters long, but sometime it is shorter.
When you're debugging it - do you see the Value change in the Code?

**Comment by cpuwolf** [comment]
I am debugging isis.MemoryOffsets["isisBaro"].GetValue() again. the result is fixed whenever I change BARO value in Fenix

double hex = 0x408FA80000000000 = 1.013

**Comment by Fragtality** [comment]
Aha - okay.
You know, when I'm being brutally honest: I can't help you like that. I'll put more effort in asking questions and trying to understand the situation than you answering them or explaining what exactly you're trying to do.
I can't help you, if you don't help my to understand the situation better. 

All I can say: the Binary is working, when used in the intended way - especially the ISIS Baro.
What is the Reason you can't use the resulting String which is created by the Binary?
Did you have a look at the other open Issue? Would an Option/Feature that outputs the Raw-Values directly (instead of a formatted string) also help with your Use-Case?

**Comment by cpuwolf** [comment]
Fenix A320 v1.0.6.146 has a different ISIS pattern layout. the issue is solved,
